-- Bibliologia – 33 questões (Graduação)
-- Módulo 1 – Revelação e Inspiração (11)
INSERT INTO questoes (curso, disciplina, modulo, aula, enunciado, a, b, c, d, e, correta, nivel) VALUES
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 1','A revelação geral refere-se:','À revelação exclusiva da Bíblia','À manifestação de Deus apenas aos profetas','À revelação de Deus na natureza e na consciência humana','À revelação através dos sacramentos','À tradição da Igreja','C','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 1','A revelação especial é caracterizada por:','Ser acessível a todos por meio da razão','Ser progressiva e culminar em Cristo','Ser contraditória','Ser apenas simbólica','Ser transmitida oralmente apenas','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 2','A inspiração bíblica significa que:','Os autores escreveram sem consciência','Deus ditou mecanicamente o texto','O Espírito Santo guiou os autores na escrita','A Bíblia contém apenas partes inspiradas','A Igreja definiu o conteúdo inspirado','C','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 2','A teoria da inspiração plenária afirma que:','Apenas ideias gerais são inspiradas','Toda a Escritura é inspirada por Deus','Apenas o Novo Testamento é inspirado','A inspiração é parcial','A Bíblia inspira moralmente apenas','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 3','Segundo 2 Timóteo 3:16, a Escritura é:','Parcialmente útil','Inspirada e proveitosa para o ensino','Apenas histórica','Somente devocional','Limitada à cultura judaica','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 3','A inspiração verbal defende que:','Apenas conceitos são inspirados','As palavras originais foram inspiradas','A Bíblia é falível','A Igreja corrige a Escritura','Somente traduções modernas são válidas','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 4','A ação do Espírito Santo na inspiração foi:','Anuladora da personalidade humana','Cooperativa e orientadora','Contraditória','Apenas simbólica','Limitada aos apóstolos','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 4','A inspiração bíblica garante:','A ausência de dificuldades textuais','A inerrância dos autógrafos','A infalibilidade das traduções','A eliminação da fé','A igualdade com outras religiões','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 5','A diferença entre revelação e inspiração é que:','Revelação é inferior à inspiração','Revelação comunica a verdade; inspiração registra','Inspiração substitui a revelação','Ambas são idênticas','Revelação é humana','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 5','A culminação da revelação divina ocorre em:','Moisés','Paulo','Jesus Cristo','João Batista','Abraão','C','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 1','Aula 5','A revelação progressiva indica que:','Deus muda de ideia','A verdade foi revelada gradualmente','A Bíblia se contradiz','O AT é inválido','A Igreja completa a revelação','B','GRADUACAO');

-- Módulo 2 – Cânon e Autoridade Bíblica (11)
INSERT INTO questoes (curso, disciplina, modulo, aula, enunciado, a, b, c, d, e, correta, nivel) VALUES
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 6','O cânon bíblico refere-se:','Aos livros apócrifos','À lista oficial dos livros inspirados','À tradição oral','À teologia sistemática','À autoridade papal','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 6','O cânon do Antigo Testamento foi reconhecido:','Pela Igreja Católica','Pelo povo judeu','No Concílio de Trento','No século XX','Pelos reformadores','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 7','Os livros apócrifos:','Foram escritos pelos apóstolos','Não fazem parte do cânon hebraico','São superiores aos canônicos','Foram inspirados posteriormente','São obrigatórios para a fé cristã','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 7','O Novo Testamento possui quantos livros?','27','39','66','73','24','A','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 7','Critérios de canonicidade do NT incluem:','Apenas popularidade','Apostolicidade, ortodoxia e uso eclesial','Idioma original','Tamanho do livro','Aceitação moderna','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 8','Autoridade normativa das Escrituras significa:','Recomendação opcional','Regra de fé e prática para a Igreja','Apenas devoção particular','Somente história','Somente ética','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 8','Sola Scriptura afirma que:','Tradição é superior','A Escritura é a única norma infalível de fé e prática','Experiência define doutrina','Concílios são inerrantes','Líderes locais decidem tudo','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 9','Reconhecimento canônico é melhor descrito como:','Criação de autoridade pela igreja','Reconhecer autoridade intrínseca dada por Deus','Voto popular secular','Vontade do imperador','Decisão acadêmica neutra','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 9','Sobre manuscritos do NT, pode-se dizer:','Existem poucos e tardios','Há grande número e antiguidade, fortalecendo confiabilidade','Não há cópias antigas','Não existem variantes','Apenas em latim','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 10','Deuterocanônicos são:','Livros inspirados por todos os ramos da fé','Textos reconhecidos por tradições específicas, sem status canônico universal','Livros apóstolos tardios','Partes perdidas do NT','Profecias secretas','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 2','Aula 10','“Norma normans” refere-se a:','Costumes locais','A Escritura como norma que normatiza outras normas','Decisões civis','Tradições familiares','Experiências subjetivas','B','GRADUACAO');

-- Módulo 3 – Confiabilidade e Interpretação (11)
INSERT INTO questoes (curso, disciplina, modulo, aula, enunciado, a, b, c, d, e, correta, nivel) VALUES
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 11','A confiabilidade bíblica é sustentada por:','Tradições religiosas','Manuscritos antigos e arqueologia','Lendas históricas','Filosofia moderna','Dogmas humanos','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 11','A arqueologia bíblica:','Contradiz a Bíblia','Confirma muitos relatos bíblicos','É irrelevante','É apenas simbólica','É antibíblica','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 12','O número de manuscritos do NT indica:','Fragilidade textual','Alta confiabilidade','Contradições doutrinárias','Corrupção do texto','Perda da inspiração','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 12','A inerrância bíblica aplica-se:','Às traduções modernas','Aos autógrafos originais','À tradição','À interpretação pessoal','À cultura atual','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 13','A interpretação correta da Bíblia exige:','Leitura literal absoluta','Princípios hermenêuticos','Rejeição do contexto','Experiência mística','Autoridade clerical','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 13','O contexto histórico auxilia:','A distorcer o texto','A compreender o significado original','A negar milagres','A atualizar a revelação','A corrigir a Bíblia','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 14','A Bíblia deve ser interpretada:','Isoladamente','À luz da própria Escritura','Somente pela filosofia','Pela tradição oral','Pela ciência moderna','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 14','A unidade da Escritura demonstra:','Contradição teológica','Coerência doutrinária','Pluralismo religioso','Erro humano','Evolução doutrinária','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 15','O objetivo da Bibliologia é:','Criar novas doutrinas','Estudar a origem e autoridade da Bíblia','Substituir a fé','Modernizar a Escritura','Eliminar a teologia','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 15','A suficiência das Escrituras afirma que:','A Bíblia é incompleta','A Bíblia é suficiente para fé e prática','A tradição é superior','A ciência corrige a Bíblia','A Igreja complementa a revelação','B','GRADUACAO'),
('Graduado em Teologia','Bibliologia','Módulo 3','Aula 15','A autoridade final para o cristão é:','A cultura','A razão','A experiência','A Palavra de Deus','A tradição eclesiástica','D','GRADUACAO');
